### ISSUE TITLE
Processing multiple JSON files

### ISSUE THREAD

**Issue by nbarrett** [damianszczepanik/cucumber-sandwich#15]
Hi there, I love cucumber sandwiches :smile: Glad you are looking after the sandwich bar so well now that @kingsleyh is not working at the counter.

Here is my problem: I am running protractor at the moment with cucumber and have multi-capabilities configured in such a way that a json file gets produced for each capability (they would contain identical content). That's great and is working fine. However when I run Cucumber Sandwich I see the two files get detected but only a single set of artifacts get produced. How do I get a report per capability please?
   >> Starting Cucumber Sandwich.....
   >> Running once only as -n flag supplied.....
   >> Found json reports: 2
   >> /Users/nick/dev/git/client/web-ui/target/protractor/cucumber/json/os_x_10_10_safari_8_results.json
   >> /Users/nick/dev/git/client/web-ui/target/protractor/cucumber/json/windows_7_chrome_47_results.json
   >> About to generate Cucumber Report into: /Users/nick/dev/git/client/web-ui/target/protractor/cucumber/json/cucumber-html-reports
   >> Finished generating Cucumber Report into: /Users/nick/dev/git/client/web-ui/target/protractor/cucumber/json/cucumber-html-reports

Oh, btw, I'm using the args: `-f target/protractor/cucumber -o target/protractor/cucumber/json -n`

**Comment by damianszczepanik** [comment]
This should be fixed now but new release should be done. Hopefully soon in PR that is currently ongoing
