### ISSUE TITLE
Can this be updated to use the new charts (Highcharts.com)?

### ISSUE THREAD

**Issue by dh14162** [damianszczepanik/cucumber-sandwich#17]
Hi,
This is a good stand alone cucumber reporting tool that mimics the Jenkins plug in one.
Would it be possible to have this updated to draw/use the same charts?
i.e In the "Feature Overview" page, the Jenkins Plugin displays 3D pie and ring charts and also has hover feature that shows the number of passing/failing/skipped steps and scenarios.
Many thanks,
dh14162

![screen shot 2016-05-26 at 10 15 07](https://cloud.githubusercontent.com/assets/11945072/15569814/d34ab0ce-232a-11e6-9f9c-140dfd9edb54.png)
![screen shot 2016-05-26 at 10 15 29](https://cloud.githubusercontent.com/assets/11945072/15569815/d34ff6d8-232a-11e6-9c8a-a2cd79d91b0e.png)

**Comment by damianszczepanik** [comment]
It is by purpose.  I don't want to have the same charts everywhere.
