### ISSUE TITLE
Fails in the Hooks

### ISSUE THREAD

**Issue by fennJam** [damianszczepanik/cucumber-sandwich#18]
Hi,

I have been using the tool for a while and it is fantastic! Thanks.

I have added some asserts into my after hooks
If one of these asserts fails the report doesn't mark the scenario as failed .
However, these are marked as fails in the console when I run the tests through the jUnit runner.
They are also highlighted when in the html cucumber report.
This may be a bit of a grey area should the scenario be marked as failed in this situation?

Thanks.

**Comment by damianszczepanik** [comment]
It does not change the status, it copied it from report so you need to make sure that scenario is failed in report
