### ISSUE TITLE
Reports dont get generated 

### ISSUE THREAD

**Issue by asmi85** [damianszczepanik/cucumber-sandwich#2]
Hey there,

So i was trying to use this plugin to generate the html reports,  i ran the jar file ...But when i ran my cucumber scripts to genrate json file ...nothing was generated ...can u please help ?

**Comment by cades** [comment]
same problem on OS X 10.10.1

**Comment by cades** [comment]
I ran `java -jar cucumber-sandwich.jar --help` and saw the following message:

```
Usage: <main class> [options]
  Options:
  * -f   Folder to monitor for cucumber.json report files
  * -o   Output directory to generate the cucumber-html-reports into
```

it says that we should provide a **folder** to -f , rather than the cucumber.json file path.

**Comment by kingsleyh** [comment]
Hi

Yes you need to -f and supply the path to the folder where the cucumber.json gets written

**Comment by kingsleyh** [comment]
The reason it's a folder and not the json file is that many json files can be generated

**Comment by cades** [comment]
yes, however a quick look at README, the following instruction

`java -jar cucumber-sandwich.jar -f path/to/the/folder/containing/cucumber.json -o /path/to/generate/html/reports/into`

seems like -f should accept the path to cucumber.json file. Maybe @asmi85 made the mistake as me.

should we make it more clear?

**Comment by kingsleyh** [comment]
Yeah sure - what do you suggest?

**Comment by cades** [comment]
`java -jar cucumber-sandwich.jar -f path/to/the/folder/that/cucumber.json/would/be/generated/at/ -o /path/to/generate/html/reports/into`

**Comment by damianszczepanik** [comment]
Try with next release
