### ISSUE TITLE
how to deal with missing steps in cucumber scenarios report?

### ISSUE THREAD

**Issue by adamcysewski** [damianszczepanik/cucumber-sandwich#20]
Hi,
What could be the reason, that some steps results are missing in cucumber scenarios report?
Actually in my case it affects Background steps

![screen shot 2016-06-15 at 5 57 47 pm](https://cloud.githubusercontent.com/assets/17701631/16087395/2a4bb4ba-3323-11e6-855e-ab311efbad47.png)

Thanks in advance for your help

**Comment by damianszczepanik** [comment]
Check with Cucumber implementation you use

**Comment by adamcysewski** [comment]
I use v. 1.0.0. for nmp https://www.npmjs.com/package/cucumber , there's still the same effect - all steps which are in Background are missing in main report.
Is there any solution for that?

**Comment by damianszczepanik** [comment]
Reports generates what you have in json file - fix the problem so tests will not generate missing status in report
