### ISSUE TITLE
Adding cucumber-sandwich.jar as dependency

### ISSUE THREAD

**Issue by BhuvaneshMani** [damianszczepanik/cucumber-sandwich#22]
I wanted to remove additional task of starting the monitor / listener for my destination report directory. Instead i made the function generateReport() as public and calling it in @After hook of cucumber so that html report gets generated. However this generates just plain reports.

Not sure if its a bug. But i dont want to use seperate window, i am trying to integrate it with my test pack.

**Comment by damianszczepanik** [comment]
Report is generated as full HTML format, check screenshots here https://github.com/damianszczepanik/cucumber-reporting

**Comment by BhuvaneshMani** [comment]
Thanks for your immediate help. I can able to configure pretty html report generation. Is there similar way to generate reports with graphs in maven project? similar to Cucumber-JVM jenkins report which has pie-chart. Jenkins report looks spectacular because of its rich appearance with pie charts, animated graphs, table of execution detail and feature file. I am stuck to generate such report using maven cucumber jvm. please help.

**Comment by damianszczepanik** [comment]
There are a few ways 
https://github.com/damianszczepanik?tab=repositories
