### ISSUE TITLE
Getting no main manifest attribute, in cucumber-sandwich-2.4.1.jar

### ISSUE THREAD

**Issue by vsainz** [damianszczepanik/cucumber-sandwich#23]
Using the following dependency in my pom.xml, it pulls down the cucumber-sandwich-2.4.1.jar. 
```
<dependency>
      <groupId>net.masterthought</groupId>
      <artifactId>cucumber-sandwich</artifactId>
      <version>RELEASE</version>
    </dependency>
```
When I then try to use it
```
java -jar ~/.m2/repository/net/masterthought/cucumber-sandwich/2.4.1/cucumber-sandwich-2.4.1.jar -n -f {myJSONfolder} -o {myOutputFolder}
```
I get this error:
**no main manifest attribute, in ~/.m2/repository/net/masterthought/cucumber-sandwich/2.4.1/cucumber-sandwich-2.4.1.jar**

I saw that you had a similar issue and suggested the latest release, but I can see in your Manifest that you do *NOT* have the Main-Class defined.
```
> cat MANIFEST.MF
Manifest-Version: 1.0
Built-By: Damian
Build-Jdk: 1.7.0_79
Created-By: Apache Maven 3.3.3
Archiver-Version: Plexus Archiver
```

**Comment by damianszczepanik** [comment]
I would have to check if this is problem with code or release.

**Comment by vsainz** [comment]
Is there anything else I can help you with? In the meantime I will rebuild it myself, and use it that way. Thank you. I believe it will be a perfect app for us!

**Comment by damianszczepanik** [comment]
You can prepare fix for this problem once the it is solved and tested locally ;)
I would be happy to merge it!

**Comment by vsainz** [comment]
Hi Damian.
I can't do this for you, because it doesn't need any changing. All you have to do is rebuild, using your master branch, and then rename, and upload the jar to the Central repository.  I can't upload for you, but if you need me to build it and attach it here? I guess I could do that?

**Comment by damianszczepanik** [comment]
I have rebuild this but main class is still not defined in manifest. Try to use `cucumber-sandwich-2.4.1-jar-with-dependencies.jar` when calling directly via console

**Comment by vsainz** [comment]
oh, that's so crazy. I'll try it out in two weeks when I'm back on this work. Thanks for working through it. I'll take a look at the jar my build produces and attach it if it has the correct manifest and lets me attach it.
