### ISSUE TITLE
Viewing a duplicate screenshot

### ISSUE THREAD

**Issue by jmcinerney** [damianszczepanik/cucumber-sandwich#26]
Hi,

There seems to be an issue when there are duplicate screenshots that exist on the same page. Only the first instance of the screenshot on the page will actually display/maximize.

As an example I have:

### Scenario 1
Given some stuff happens
Then I should be able to view this screenshot
_Screenshot 1_

### Scenario 2
Given some stuff happens
Then something else might happen

### Scenario 3
Given some stuff happens
Then I should be able to view this screenshot
_Screenshot 1_

In this case suppose the two screenshots are exactly the same. When I click on the screenshot link in Scenario 3 it will instead expand the screenshot in Scenario 1. This seems to be an ongoing issue and has been prevalent in the past few versions I have used.

This issue is exacerbated in the latest version given that scenario text is collapsed/hidden by default. In previous versions the page would shift vertically, hinting that something else had been expanded further up on the screen. Now that the reports are collapsed there is no hint that something else has expanded and even if you knew to look above you would not know which report to look in given that the screenshot is still hidden within a collapsed scenario.

**Comment by damianszczepanik** [comment]
Was fixed in damianszczepanik/cucumber-reporting/pull/460
