### ISSUE TITLE
Data table's not in report

### ISSUE THREAD

**Issue by humphreyn** [damianszczepanik/cucumber-sandwich#27]
Hi Damian,

I recently upgraded to the latest version stand-alone cucumber report (2.8.0) and now the report does not display any test scenario data tables from my feature file. Is this a known issue/bug?

**Comment by damianszczepanik** [comment]
No, I need more details

**Comment by humphreyn** [comment]
Hi Damian,

My automation test framework is based on Cucumberjs along with protractor running on Node.js

Locally I use Bower with ‘F’ flag to force update to the latest version of your standalone version of the cucumber sandwich reporting tool, below is the bower json dependency file:

{
  "name": "automation",
  "version": "0.0.0",
  "authors": [
    "humphreyn <neville.humphrey@rbi.co.uk>"
  ],
  "description": "Test Automation",
  "dependencies": {
    "cucumber-sandwich": "https://github.com/damianszczepanik/cucumber-sandwich.git"
  }
}


I then have a gulp task that runs maven to build the reporting tool and rename the jar file:


gulp.task('build:cucumber-sandwich', function (cb) {
  var dir = 'bower_components/cucumber-sandwich';

  const mvn = require('maven').create({
    cwd: dir,
    quiet: false,
    updateSnapshots: true
  });

  mvn.execute(['clean', 'install'], { 'skipTests': false })
    .then(() => {
      gulp.src( dir + '/target/cucumber-sandwich-*-SNAPSHOT-jar-with-dependencies.jar')
        .pipe(rename('cucumber-sandwich.jar'))
        .pipe(gulp.dest( dir + '/target'))
        .on('error', function(e) {
          cb();
          throw e;
        })
        .on('stop', function() {
          this.emit('end');
        })
        .on('end', function() {
          cb();
        });
    });
});


If I run the following test scenario which has a two data tables, one in the background and another in the scenario itself:


Background: A user with an organisation and business
    Given an organisation with the following "businesses":
        | Business name         | Reference | Country        |
        | Sutton Park Farm Ltd  | SPF       | United Kingdom |

Scenario: Verify field tab order on Equipment add drawer
    And I am on the "Equipment add" page
    Then the tab order should be as follows:
        | Equipment Name    |
        | Type              |
        | Reference         |
        | Is Self Propelled |
        | Close             |
        | Done              |


The json output is fine and does contain the data table argument cells, see attached. But the html report does not, see screenshot below. Note I also have a Before and After step from Hooks.




[cid:image001.jpg@01D21430.EAC7E400]
If you need anything more let me know.

Regards,
Neville

**Comment by damianszczepanik** [comment]
Attach JSON file and list elements that are not present. Mind that this report is dedicated for Cucumber-JVM not Cucumber-JS implementation so some elements may not be supported.

**Comment by damianszczepanik** [comment]
I've just checked and the sample data https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/test/resources/json/sample.json#L67-L103 is displayed properly. If you still have this problem raise the issue in main project https://github.com/damianszczepanik/cucumber-reporting
