### ISSUE TITLE
Error message is not escaped

### ISSUE THREAD

**Issue by vikramuk** [damianszczepanik/cucumber-sandwich#29]
Hi Good Day Damian,
   I have reported this observation on the Google Cukes forum where the Junit assert statement errors are not fully reported on cucumber reports.

Link: https://groups.google.com/forum/#!topic/cukes/SaiUmv7Nd8k

Current Environment: Cukes 1.2.5 and Junit4.12 along with JenkinsPlugin3.0

Kindly let me know if this can be resolved.

Details: 
I tried to generate the Cucumber-Sandwich report from https://github.com/damianszczepanik/cucumber-sandwich

I still see the Issue with latest jar's and with the Cucumber JVM PluginVersion 3.0
https://wiki.jenkins-ci.org/display/JENKINS/Cucumber+Reports+Plugin

Given LotusApplication is Installed on connected Android Device015ms
Error message
java.lang.AssertionError: expected: **but was:**
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(
Assert.java:144)
	at StepDefinition.Test_Steps.LotusAppInstalled(Test_Steps.java:79)
	at ✽.Given LotusApplication is Installed on connected Android Device(Feature/Test.feature:8)

Actual Source:
<div id="msg-10" class="collapse collapsable-details">
<pre>java.lang.AssertionError: expected:<true> but was:<false>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:118)
at org.junit.Assert.assertEquals(Assert.java:144)
at StepDefinition.Test_Steps.LotusAppInstalled(Test_Steps.java:79)
at ✽.Given LotusApplication is Installed on connected Android Device(Feature/Test.feature:8)

**Comment by damianszczepanik** [comment]
I thought I have already fixed that as it was reported. Attach json file so I can confirm and fix it if needed.

**Comment by vikramuk** [comment]
Hi Damian,
  Please find the Files. 
Current Issue reported on Groups: https://groups.google.com/forum/#!topic/cukes/SaiUmv7Nd8k
[cucumber-html-reports.zip]

Ran: D:\ProgApps>java -jar  cucumber-sandwich.jar   -n -f \BDD   -o \BDD\CucumberReport
Project 
[cucumber-html-reports.zip](https://github.com/damianszczepanik/cucumber-sandwich/files/508319/cucumber-html-reports.zip)
Dependencies:
gherkin-2.12.2.jar
hamcrest-all.jar
junit-4.12.jar
jacob-1.14.3.jar
TestComplete.jar
cucumber-core-1.2.5.jar
cucumber-html-0.2.3.jar
cucumber-java-1.2.5.jar
cucumber-java8-1.2.5.jar
cucumber-junit-1.2.5.jar
cucumber-jvm-deps-1.0.5.jar

**Comment by vikramuk** [comment]
Hi Damian,
 When would this fix be available with the jenkins build<https://wiki.jenkins-ci.org/display/JENKINS/Cucumber+Reports+Plugin>?. Or with the Cucumber-sandwich jar code?.

**Comment by damianszczepanik** [comment]
Now, wait for Jenkins sync.
