### ISSUE TITLE
main manifest ?

### ISSUE THREAD

**Issue by sgmadurai** [damianszczepanik/cucumber-sandwich#39]
Hi, when i run the jar, it just says there is no main manifest in jar (i used 3.8.0)

**Comment by damianszczepanik** [comment]
Try to run jar with dependencies

**Comment by hazendaz** [comment]
@damianszczepanik I know this was raised and closed but wondered if you could do anything to help better prevent this situation.  Unfortunately I think too many people fail to read the basics of any git repo readme which you do clearly state to use the classified jar.  I'm not sure if you can introduce something in that core jar that might simply spit out an error that wrong one is used and to go use the right one.  I didn't run into that issue myself as I read what you had and it was rather clear but another person at my work spent half a day wasting time, trying everything but reading your site before asking me about it and I got them going in about 10 minutes.  I'd personally love for those that fail to do the bare bones research from wasting their own time as well as mine and others asking silly questions.  I'm thinking a simple main in this core jar that reports out the instructions to use the other might work but not familar at all with the library right now to know if that would cause other issues.

**Comment by hazendaz** [comment]
I should note version tried was 3.9.0 just in case this is something that later exists.

**Comment by damianszczepanik** [comment]
Release produces different jars for different purposes. I'm happy to accept any readme/tip/other that help developers use correct vversion
