### ISSUE TITLE
cucumber-sandwich does not correctly handle UTF-8

### ISSUE THREAD

**Issue by rkraneis** [damianszczepanik/cucumber-sandwich#4]
To correctly handle UTF-8 in `cucumber.json` `cucumber-sandwich.jar` has to be called with `-Dfile.encoding=UTF-8` despite the fact that JSON defaults to using UTF-8 and that the created HTML advertises `text/html; charset=UTF-8` (this is on Windows 7 with a default encoding of `Windows-1252`).

**Comment by damianszczepanik** [comment]
Should be fine right now
