### ISSUE TITLE
when a scenario has a step that returns 'pending' that the cucumber reports show the scenario as 'failed'.

### ISSUE THREAD

**Issue by sbpk516** [damianszczepanik/cucumber-sandwich#47]
We've 
![cucumber_report_pendingscenarios](https://user-images.githubusercontent.com/26196461/36121270-a182018c-1013-11e8-81e2-0fd37a61f4de.png)
noticed that when a scenario has a step that returns 'pending' that the cucumber reports show the scenario as 'failed'. Is there a way to change that behavior? We use 'pending' to indicate that a certain dependency is not configured during a particular test run, and this is an expected condition 

Reference:https://github.com/damianszczepanik/cucumber-reporting/pull/636

**Comment by damianszczepanik** [comment]
Yes, this is duplicate
