### ISSUE TITLE
How to integrated with Automation Framework using  POM Dependency

### ISSUE THREAD

**Issue by vishalanand1** [damianszczepanik/cucumber-sandwich#48]
I need to integrate cucumber-sandwich to my maven project and execute it from the framework after my test run , as i see from github it doesnt have the mechanism to run , not details on how to 
integrate it with the POM file and execute it. Can you please guide , i am new to this ...

**Comment by damianszczepanik** [comment]
What I can ofer is the README file. If you find something interesting what is not there, please complete instruction - I will be happy
