### ISSUE TITLE
how to embed screenshot into cucumber sandwich report ? 

### ISSUE THREAD

**Issue by sab3d** [damianszczepanik/cucumber-sandwich#6]
Below code, 
embed("data:image/png;base64,#{encoded_img}",'image/png', "ERROR SCREENSHOT:#{time}:#{@feature_name}_feature_at_#{name_of_scenario}")

embeds screenshot in html report successfully but when i try to embed in json report, it fails. 
is there a different approach to embed screenshot in cucumber sandwich report ?

**Comment by damianszczepanik** [comment]
You need to encode screenshot as Base64 format
