### ISSUE TITLE
Reporting- How to add logs to Steps? 

### ISSUE THREAD

**Issue by jiten0811** [damianszczepanik/cucumber-sandwich#67]
Log.info is not showing logs under Step Defination files, is there Reported that i can use ? 
i am using Latest version of Cucumber-Sandwich.

![image](https://user-images.githubusercontent.com/47103238/55876171-9c895e80-5bb4-11e9-8db9-b1f7a7850e0f.png)

**Comment by damianszczepanik** [comment]
Attach JSON file

**Comment by jiten0811** [comment]
Here you go sir!
[CucumberJitendra.txt](https://github.com/damianszczepanik/cucumber-sandwich/files/3076062/CucumberJitendra.txt)

**Comment by damianszczepanik** [comment]
You need to store that data into JSON file so the report can display it

**Comment by jiten0811** [comment]
I am storing this data in JSON only under my project strtuctre and calling it in ithis method


public static void reportKill() throws Exception {

		// String projectPath = System.getProperty("user.dir");
		String command = "java -jar cucumber-sandwich.jar -f target\\cucumber-reports -o target\\cucumberHTML -n";

		Process p = Runtime.getRuntime().exec(command);
		  String[] browserExe = { "chromedriver.exe", };
		  Runtime.getRuntime().exec("taskkill /F /IM " + browserExe);

![image](https://user-images.githubusercontent.com/47103238/56080514-b5497c80-5e1f-11e9-81a3-77357883c7d0.png)
