### ISSUE TITLE
Embeddings on reports are showing corrupt in html

### ISSUE THREAD

**Issue by rayk47** [damianszczepanik/cucumber-sandwich#70]
I have a report where I am attaching text/plan to both the after hooks and also in step definitions for cucumberJs. A sample of the json generated in the report is as follows
`[
    {
      "description": "  Test",
      "keyword": "Feature",
      "name": "Test 1",
      "line": 2,
      "id": "test-1",
      "tags": [
        {
          "name": "@test1",
          "line": 1
        }
      ],
      "uri": "test/feature/test1.feature",
      "elements": [
        {
          "id": "test-1-feature-sceanrio",
          "keyword": "Scenario",
          "line": 26,
          "name": "test 1 feature scenario",
          "tags": [
            {
              "name": "@test1",
              "line": 1
            },
            {
              "name": "@testSceanrio",
              "line": 23
            },
            {
              "name": "@tag2",
              "line": 23
            }
          ],
          "type": "scenario",
          "steps": [
            {
              "keyword": "Before",
              "hidden": true,
              "match": {
                "location": "test/support/Hooks.js:89"
              },
              "result": {
                "status": "passed",
                "duration": 1000000
              }
            },
            {
              "keyword": "Before",
              "hidden": true,
              "match": {
                "location": "test/support/Hooks.js:105"
              },
              "result": {
                "status": "passed",
                "duration": 3000000
              }
            },
            {
              "arguments": [],
              "keyword": "Given ",
              "line": 8,
              "name": "I perofrm a test",
              "match": {
                "location": "test/stepDefinitions/login/Login.js:44"
              },
              "result": {
                "status": "passed",
                "duration": 1410000000
              }
            },
            {
              "arguments": [
                {
                  "rows": [
                    {
                      "cells": [
                        "data1",
                        "data2",
                        "data3",
                        "data4"
                      ]
                    },
                    {
                      "cells": [
                        "data1",
                        "data2",
                        "data3",
                        ""
                      ]
                    }
                  ]
                }
              ],
              "keyword": "And ",
              "line": 9,
              "name": "I have a test creaed",
              "match": {
                "location": "test/stepDefinitions/common/CommonDataPrep.js:51"
              },
              "result": {
                "status": "passed",
                "duration": 16178000000
              },
              "embeddings": [
                {
                  "data": "Test this",
                  "mime_type": "text/plain"
                },
                {
                  "data": "TestName: Test A TestId: 123",
                  "mime_type": "text/plain"
                }
              ]
            },
            {
              "arguments": [
                {
                  "rows": [
                    {
                      "cells": [
                        "data1",
                        "data2",
                        "data3",
                        "data4",
                        "data5",
                        "data6",
                        "data7",
                        "data8",
                        "data9"
                      ]
                    },
                    {
                      "cells": [
                        "data1",
                        "data2",
                        "data3",
                        "data4",
                        "data5",
                        "data6",
                        "data7",
                        "data8",
                        "data9"
                      ]
                    }
                  ]
                }
              ],
              "keyword": "And ",
              "line": 12,
              "name": "I finish test",
              "match": {
                "location": "test/stepDefinitions/common/CommonDataPrep.js:72"
              },
              "result": {
                "status": "failed",
                "duration": 60010000000,
                "error_message": "Error: function timed out, ensure the promise resolves within 60000 milliseconds\n    at Timeout._time.default.setTimeout [as _onTimeout] (/Users/raymondkelly/WebstormProjects/quotepad-service/node_modules/cucumber/lib/user_code_runner.js:81:20)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:290:5)"
              }
            },
            {
              "arguments": [
                {
                  "rows": [
                    {
                      "cells": [
                        "data1",
                        "data2",
                        "data3",
                        "data4",
                        "data5"
                      ]
                    },
                    {
                      "cells": [
                        "data1",
                        "data2",
                        "data3",
                        "data4",
                        "data5"
                      ]
                    },
                    {
                      "cells": [
                        "data1",
                        "data2",
                        "data3",
                        "data4",
                        "data5"
                      ]
                    },
                    {
                      "cells": [
                        "data1",
                        "data2",
                        "data3",
                        "data4",
                        "data5"
                      ]
                    }
                  ]
                }
              ],
              "keyword": "When ",
              "line": 15,
              "name": "I did the test",
              "match": {
                "location": "test/stepDefinitions/quoting/ContributionStrategy.js:40"
              },
              "result": {
                "status": "skipped"
              }
            },
            {
              "arguments": [
                {
                  "rows": [
                    {
                      "cells": [
                        "data1"
                      ]
                    },
                    {
                      "cells": [
                        "data1"
                      ]
                    }
                  ]
                }
              ],
              "keyword": "Then ",
              "line": 20,
              "name": "everything is complete",
              "match": {
                "location": "test/stepDefinitions/quoting/QuoteCensus.js:105"
              },
              "result": {
                "status": "skipped"
              }
            },
            {
              "keyword": "After",
              "hidden": true,
              "match": {
                "location": "test/support/Hooks.js:122"
              },
              "result": {
                "status": "passed",
                "duration": 1000000
              },
              "embeddings": [
                {
                  "data": "Test this after",
                  "mime_type": "text/plain"
                }
              ]
            }
          ]
        }
      ]
    }
  ]`

I have reviewed the code and tests in https://github.com/damianszczepanik/cucumber-reporting and the json appears to be in the correct format however when I generate the report the attachment in the report shows as `M�-��`

I have tested this with cucumber-reporting-4.7.0 and cucumber-reporting-4.6.0 and have the same issue. Attached below is an image of the html 
<img width="766" alt="Screen Shot 2019-05-24 at 11 24 28 AM" src="https://user-images.githubusercontent.com/10120831/58348841-94107e80-7e16-11e9-90cf-79c4f524c755.png">

**Comment by damianszczepanik** [comment]
Attachments are not encoded with base64

**Comment by rayk47** [comment]
Ah of course. TY.

**Comment by dawn-minion** [comment]
@damianszczepanik I know it's an old issue, but just came across this - why is embedded data with a mime of `text/plain` expected to be in base64 format? I'm using this with Cucumber JS, and I can't see anything in their docs expecting things to be attached in base64 format other than actual binary data.

**Comment by damianszczepanik** [comment]
JVM implementations expect it that way. Maybe JS is different.

**Comment by dawn-minion** [comment]
Ah, fair enough then if that's the case :+1:

**Comment by damianszczepanik** [comment]
You can open new issue if this feature is wanted
