### ISSUE TITLE
Unable to access jarfile cucumber-sandwich.jar

### ISSUE THREAD

**Issue by Ravi2605** [damianszczepanik/cucumber-sandwich#85]
While trying run the generate report command as mentioned in the documentation ,we are getting below error not sure what iam missing here?

Saw the jar with 5.3.1 with dependencies created and renamed to cucumber-sandwich.jar and tried to run the jar file to test but getting below error all the time.

cucumber-sandwich thopukr$ java -jar cucumber-sandwich.jar
Error: Unable to access jarfile cucumber-sandwich.jar

**Comment by damianszczepanik** [comment]
Well then there is something wrong with access or content of the jar file
